apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dws-ticket-service-production
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  source:
    repoURL: https://github.com/dws-org/gitops.git
    targetRevision: HEAD
    path: gitops-demo/dws-ticket-service-app
    helm:
      valueFiles:
        - ../environments/production/ticket-service/values.yaml
  
  destination:
    server: https://kubernetes.default.svc
    namespace: dws-ticket-service
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
